universe = vanilla
executable = inference_pipeline.sh

log = logs/inference_pipeline.log
output = logs/inference_pipeline_$(Cluster).out
error = logs/inference_pipeline_$(Cluster).err

transfer_input_files = inference_inputs/

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

Requirements = (Target.HasCHTCStaging == true)

# testing requirements
request_memory = 16GB
request_disk = 8GB
request_cpus = 4
request_gpus = 1
+GPUJobLength = "short" 
+WantGPULab = true
gpus_minimum_capability = 8.0
+is_resumable = true

arguments = 1 

queue

